### ISSUE TITLE
Merge theme engine v2 in as a component

### ISSUE THREAD

**Issue by garyc40** [wp-e-commerce/WP-e-Commerce#848]
For 3.9 release, theme engine v2 should be merged in early in the cycle so that it can be tested and improved upon conveniently.

**Comment by JustinSainton** [comment]
@misulicus You noted the following:

`Fatal error: Call to a member function get_option() on a non-object in D:\wamp\www\wpec-dev\wp-content\plugins\WP-e-Commerce-master\wpsc-admin\includes\purchase-log-list-table-class.php on line 58`

I have not been able to replicate or even find that line of code or error.  I assume we're set there now?

**Comment by JustinSainton** [comment]
@misulicus Also from your notes: `Checkout shipping is not added `.  Your dropbox link no longer works, but I had no problem with shipping being added at checkout.

**Comment by JustinSainton** [comment]
@misulicus Again, from your notes, unable to replicate the following:

`Changing order status in admin for an incomplete order (test gateway)`.

If you could re-test these last few issues, that would be super helpful - thanks!

**Comment by JustinSainton** [comment]
@misulicus `Copy billing details button does not do anything at all`

Not experiencing that - can you confirm?

**Comment by JustinSainton** [comment]
@misulicus Not sure what this means without the screenshot context: `Your Account (default page - Orders) is weird`.

As of 305ab40, a lot of things should be working better than they were, including this.

**Comment by JustinSainton** [comment]
@misulicus With regards to the issue about setting the storefront home page and getting the notice - I don't get a notice.  I get a 404 not found.  I'm thinking we need to flush permalinks when this setting is updated.  Let me know if you're still getting the notice.

**Comment by JustinSainton** [comment]
Autocomplete is sort of wonky - I think if we're going to enable JS autocomplete, we need to disable browser autocomplete.  We should check how this works on the included script site, but right now, the UX is weird.

![autocomplete](https://cloud.githubusercontent.com/assets/1168754/7032940/2287eee6-dd2b-11e4-928f-2389e4fe1c99.gif)

**Comment by jbeales** [comment]
Is an external script being used for autocomplete, or is it home-grown? 

Some browsers that support the DataList element are smart enough to combine DataList suggestions with Autocomplete suggestions, but if DataList isn't being used this problem will still exist, (and since Safari doesn't support DataList there will be times when the problem pops up).

**Comment by JustinSainton** [comment]
@jbeales It's external - https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-components/theme-engine-v2/theming/assets/js/jquery.select-to-autocomplete.js

Not a bad script, but it does not utilize DataList, and if browser support is spotty for it, then that's okay by me.

**Comment by jbeales** [comment]
Looks like it'll just copy an autocomplete attribute from the select to the generated field. If someone knows where to find the select it'll be faster for you to add it than for me to find the select & do it.

**Comment by JustinSainton** [comment]
Ahhh, crap . It's a chrome bug.

**Comment by JustinSainton** [comment]
See https://core.trac.wordpress.org/ticket/24364

**Comment by JustinSainton** [comment]
@misulicus Regarding https://github.com/WP-e-Commerce/WP-e-Commerce/issues/848#issuecomment-90708463, see #1832.

**Comment by JustinSainton** [comment]
@misulicus Re: `Edit product variation box notice` - I edited product variations several times on the product edit page, and got no notices.

**Comment by JustinSainton** [comment]
@misulicus Also, `When a field is set as required it should show the red * next to it. ` - that's already happening, please confirm.

**Comment by JustinSainton** [comment]
@misulicus Also, re `Empty required field validation message maybe should be red for ease of access `

http://cl.ly/image/3H3p1Q400A2s

**Comment by JustinSainton** [comment]
6723610 should fix `"Viewing product" is pagination text on customer account orders table page. It doesn't appear to be working as expected.`

**Comment by JustinSainton** [comment]
#1738 seems to be fixed at this point.  Not sure which commit :fried_shrimp:

**Comment by JustinSainton** [comment]
Regions also seem to be saved now :+1:

**Comment by JustinSainton** [comment]
External rates are good now.

**Comment by JustinSainton** [comment]
Noting here for posterity - leaving wizard steps as-is `Going back a step does not reflect the active step` - it does in fact add a `active` class, so we can leave the styling of this class to themes.

**Comment by JustinSainton** [comment]
@misulicus FWIW, this bug: 

```
 Tested a payment with Paypal Standard Sandbox mode. Payment went OK. Was returned to a /results/?sessionid page and order was still "pending". Tried to refresh the page and it redirected me to /store/ with empty cart message. Admin sales log still shows order as Incomplete sale (5 mins later) with IPN enabled
```

I was _only_ able to replicate this when clicking the "return to store" link on the PayPal page.  When auto-returning, it works fine.

In the 1.0 engine, however, it works either way.  Definitely worth investigating further.

**Comment by misulicus** [comment]
yeah i was clicking return to store too when i saw that

**Comment by JustinSainton** [comment]
With the last remaining known issues stubbed off, we can finally close this ticket :dancers:
